package config

// Configuration is the main configuration struct
type Configuration struct {
	Spec          int           `yaml:"spec" hc:"Spec version - Do not edit this - It will cause the application to overwrite the config files\nCurrent spec version: 1"`
	General       General       `yaml:"General" hc:"Welcome to the NextLaunch configuration file!\nThis file was automatically generated by NextLaunch, and whilst it is human-readable, it is not recommended to edit it directly.\nInstead, please use the built-in configuration editor to make changes, so that your changes are saved correctly.\nFor more information, see https://git.archimedia.uk/Altrius/nextlaunch/-/wikis/Configuration\n\nGeneral settings"`
	Database      Database      `yaml:"Database" hc:"Database settings\nNextLaunch will cache information to the database, so it can be accessed quickly,\neven when the application is not able to connect to the internet."`
	LaunchLibrary LaunchLibrary `yaml:"LaunchLibrary" hc:"Launch Library settings\nLaunch Library is a public service that provides information about upcoming and historical launches.\nIt is free to use, however you will need an API key to have higher limits. You can get one here: https://www.patreon.com/TheSpaceDevs"`
	Snapi         Snapi         `yaml:"Snapi" hc:"SNAPI - The Spaceflight News API - is a public service that provides spaceflight news.\nIt is also operated by The Space Devs and is free to use."`
	ErrorLogging  ErrorLogging  `yaml:"ErrorLogging" hc:"Error logging settings\nError logging is used to provide information about errors that occur in the application.\nThis information is used to help me to fix bugs and improve the application.\nIt is completely anonymous and will not contain any personal or sensitive information."`
	Telemetry     Telemetry     `yaml:"Telemetry" hc:"Telemetry settings\nTelemetry is used to collect anonymous usage data and helps me to improve the application.\nThis data is completely anonymous and will not contain any personal or sensitive information.\n\nTelemetry levels:\n0 - None, disabled, nothing will be sent back to the developers.\n1 - Basic, information like:\n  > CPU model\n  > OS\n  > memory usage\n  > IP Address\n  > Country\n  > Language\n\n2 - Verbose, all the things in level 1, as well as:\n  > LL2 Token presence\n  > Update frequency\n  > And other detailed information about this application.\n\nThis data does not contain any personal information, but it will be used to improve the application for you, and everyone else who uses it."`
	Keybindings   KeyBindings   `yaml:"Keybindings" hc:"Keybindings settings\nKeybindings are defined using VIM notations - See https://vimdoc.sourceforge.net/htmldoc/intro.html#key-notation\nAn action can be defined with multiple keys, but only one action may be defined for each pattern\nThe order of the keys is important, as it defines the priority of the key\nactions are defined in the following format: <namespace>.<action> - <namespace> is the namespace of the action, and <action> is the name of the action\nthe following namespaces are defined:\nprogram - actions that are related to the program\nnews - actions that are related to the news\nlaunch - actions that are related to the launches\nsettings - actions that are related to the settings\n\nMore actions may be added in the future"`
}

type General struct {
	LogLevel string `yaml:"log_level" hc:"Log level - Debug, Info, Warning, Error, Fatal - Default is Info"`
	Language string `yaml:"language" hc:"Language to use for the application - See https://git.archimedia.uk/Altrius/nextlaunch/-/wikis/Supported-Languages for a list of supported languages"`
}

type Database struct {
	DatabaseLocation string `yaml:"database_location" hc:"Location of the database to use"`
}

type LaunchLibrary struct {
	LaunchLibraryKey string `yaml:"launch_library_key" hc:"LL2 API Key"`
	CacheToDatabase  bool   `yaml:"cache_to_database" hc:"Cache the launches to the database - This allows NextLaunch to work without an internet connection (but it will be less accurate)"`
	UpdateFrequency  uint16 `yaml:"update_frequency" hc:"How often to check for updates in minutes (0 = disabled | 15 = every 15 minutes | minimum = 5 | maximum = 60)"`
}

type Snapi struct {
	EnableSnapi     bool   `yaml:"enable_snapi" hc:"Enable Snapi"`
	UpdateFrequency uint16 `yaml:"update_frequency" hc:"How often to check for updates in minutes (0 = disabled | 15 = every 15 minutes | minimum = 5 | maximum = 60)"`
}

type ErrorLogging struct {
	LogErrors       bool   `yaml:"log_errors" hc:"Log errors"`
	LogFileLocation string `yaml:"log_file_location" hc:"Log file location"`
	AutoShareErrors bool   `yaml:"auto_share_errors" hc:"Auto share errors"`
}

type Telemetry struct {
	EnableTelemetry bool   `yaml:"enable_telemetry" hc:"Enables telemetry - This will send anonymous usage data to the devs"`
	TelemetryLevel  uint16 `yaml:"telemetry_level" hc:"0 = None, 1 = Basic, 2 = Verbose"`
}

type KeyBindings = map[string][]string
