# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Compile and Release

on:
  push:
  pull_request:

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Bump Versions
        uses: michmich112/version-bumper@master
        with:
          options-file: './version-rules.json'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get build version
        id: build-version
        uses: michmich112/extract-version@main
        with:
          version-file: './version.txt'
          schema: major.minor.build

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'

      - name: Build
        run: go build -v -ldflags="-s -w -X 'main.version=1.0.0'" -o NextLaunch

#      - name: Test
#        run: go test -v ./...
